### ISSUE TITLE
Restructure folders

### ISSUE THREAD

**Issue by Nautman** [digitalungdom-se/natklok#21]
Folder structure usually comes down to taste, and there isn't a right answer on how a project should be structured.

If I were to choose on how to structure the project, I would use a flat structure in the components folder. Everything in the `src/components/general` would be `src/components`. I would place `src/components/features` in `src/features` and `src/components/slides` in `src/features/slides`.

I think a components folder that is distinctly *reusable* components is easier to understand; without having any sources on this, I believe it's more common.

**Comment by charlesmaddock** [comment]
This is definitely better, could you fix this once I've merged the branch I'm working on now? I always find it hard doing restructures like this since imports get messed up. Maybe you have a painless way of doing it.

Could you perhaps fix the bundle issue whilst your at it? (If you have time for any of these things of course :) )

**Comment by Nautman** [comment]
I can fix it!

**Comment by charlesmaddock** [comment]
Fixed in final-update-v1 branch
